# spring configuration
spring:
  application:
    name: mysite

  # devtools - live reload
  devtools:
    livereload:
      enabled: true

  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /assets/**
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  web:
    resources:
      static-locations: classpath:/assets/, file:/mysite-uploads/

  #multipart
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

    #message resource (internationalization, i18n)
  messages:
    always-use-message-format: true
    basename: messages/messages_ko
    encoding: UTF-8

  #aop
  aop:
    auto: true
    proxy-target-class: true


  #localhost:8080/mysite06/assets/images/loopy.png
  #datasource
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: mariadb://192.168.0.182:3307/webdb?charset=utf8
    username: webdb
    password: webdb
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20

# mybatis
mybatis:
  config-location: classpath:mybatis/configuration.xml


# server
server:
  port: 8088
  servlet:
    context-path: /mysite06
    encoding:
      charset: utf-8
      enabled: true